# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# version of configuration file (required)
version: 2

# Build documentation in the docs/ directory with mkdocs
mkdocs:
  configuration: mkdocs.yml

# also build docs in PDF format
formats: [pdf]

# Optionally set the version of Python and requirements required to build your docs
python:
  version: 3.7
  install:
      #      - method: pip
      #  path: .
      - requirements: docs/requirements.txt
